name: Create Release Zip
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      name: Use Node.js 16
      with:
        node-version: 16
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: build
        filename: scvmwrangler.zip
