name: Create Release Zip
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      name: Use Node.js 16
      with:
        node-version: 16
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - name: Create Zip File
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: build
        filename: scvmwrangler.zip
    - uses: ncipollo/release-action@v1.12.0
      name: Upload Zip File to GitHub
      with:
        artifacts: scvmwrangler.zip
        token: ${{ secrets.GITHUB_TOKEN }}
